import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";
import classes from "../styles/Home.module.css";

export default function Home() {
  const posts = [
    {
      title: "First Chaindustry post: This is a test, test test test test",
      img: "test.JPG",
      date: new Date().toISOString(),
      tags: [],
    },
    {
      title: "Second Chaindustry post: This is a test, test test test test",
      img: "emma.JPG",
      date: new Date().toISOString(),
      tags: ["Web3", "Finance", "Crypto"],
    },
  ];
  return (
    <div className={classes.container}>
      <Head>
        <title>Chaindustry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className={classes.intro}>
          Chaindustry is a goal, is a goal, is a goal, is a goal.
        </section>
        <div>
          {posts.map((p, id) => {
            return <Card key={id} {...p} />;
          })}
        </div>
      </main>
    </div>
  );
}
